print(" A\n B\t C \n D \t E \t F \n G \t H \t I \t J \n K \t L \t M \n N \t O \n P")
print("new line")
print("A")
print("B C")
print("D E F")
print("G H I J ")
print("K L M N")
print("O P Q R S")
print("T U V W X Y Z")